### PR TITLE
merge CONTRIBUTING.md into README.md

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by adriaanm** [comment]
We should keep a CONTRIBUTING file so that users will get a reminder of what we'd like a bug report to look like. The README could be shorter and link to CONTRIBUTING.

**Comment by SethTisue** [comment]
Doh, I had forgotten that the GitHub UI links to CONTRIBUTING.md here, when you open a new issue:
screen shot 2017-10-12 at 2 29 17 pm

I'll revise.

**Comment by SethTisue** [comment]
okay, ready for re-review

**Comment by SethTisue** [comment]
trying again with something similar: #12173

**Pull request merged**
